#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/trycourier/courier-go/v4,github.com/stainless-sdks/courier-go/v4"

echo "==> Building courier"
go build ./cmd/courier
