#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/trycourier/courier-go,github.com/stainless-sdks/courier-go"

go run ./cmd/courier "$@"
