name: CI
on:
  push:
    branches:
      - '**'
      - '!integrated/**'
      - '!stl-preview-head/**'
      - '!stl-preview-base/**'
      - '!generated'
      - '!codegen/**'
      - 'codegen/stl/**'
  pull_request:
    branches-ignore:
      - 'stl-preview-head/**'
      - 'stl-preview-base/**'

env:
  GOPRIVATE: github.com/trycourier/courier-go,github.com/stainless-sdks/courier-go

jobs:
  lint:
    timeout-minutes: 10
    name: lint
    runs-on: ${{ github.repository == 'stainless-sdks/courier-cli' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.fork) && (github.event_name != 'push' || github.event.head_commit.message != 'codegen metadata')

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-go
        with:
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Link staging branch
        if: github.repository == 'stainless-sdks/courier-cli'
        run: |
          ./scripts/link 'github.com/stainless-sdks/courier-go@${{ github.ref_name }}' || true

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Run lints
        run: ./scripts/lint

  build:
    timeout-minutes: 10
    name: build
    permissions:
      contents: read
      id-token: write
    runs-on: ${{ github.repository == 'stainless-sdks/courier-cli' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.fork) && (github.event_name != 'push' || github.event.head_commit.message != 'codegen metadata')
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-go
        with:
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Link staging branch
        if: github.repository == 'stainless-sdks/courier-cli'
        run: |
          ./scripts/link 'github.com/stainless-sdks/courier-go@${{ github.ref_name }}' || true

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          version: latest
          args: release --snapshot --clean --skip=publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get GitHub OIDC Token
        if: |-
          github.repository == 'stainless-sdks/courier-cli' &&
          !startsWith(github.ref, 'refs/heads/stl/')
        id: github-oidc
        uses: actions/github-script@v8
        with:
          script: core.setOutput('github_token', await core.getIDToken());

      - name: Upload tarball
        if: |-
          github.repository == 'stainless-sdks/courier-cli' &&
          !startsWith(github.ref, 'refs/heads/stl/')
        env:
          URL: https://pkg.stainless.com/s
          AUTH: ${{ steps.github-oidc.outputs.github_token }}
          SHA: ${{ github.sha }}
        run: ./scripts/utils/upload-artifact.sh

  test:
    timeout-minutes: 10
    name: test
    runs-on: ${{ github.repository == 'stainless-sdks/courier-cli' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-go
        with:
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Link staging branch
        if: github.repository == 'stainless-sdks/courier-cli'
        run: |
          ./scripts/link 'github.com/stainless-sdks/courier-go@${{ github.ref_name }}' || true

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Run tests
        run: ./scripts/test
