name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "github_tag_ref=${GITHUB_TAG_REF#v}" >> "$GITHUB_OUTPUT"
        id: transform_tag
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: "20.14.0"
          scope: "@trycourier"
          always-auth: true
      - uses: MathieuSoysal/replace-string-in-file@v1.1.0
        with:
          file: source/version.ts
          old-string: local
          new-string: ${{ steps.transform_tag.outputs.github_tag_ref }}
      - run: yarn
      - run: yarn build
      - run: yarn publish --new-version ${{ steps.transform_tag.outputs.github_tag_ref }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
